apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portainer-cert
  namespace: portainer
spec:
  secretName: portainer-tls
  commonName: app.homelab.me
  dnsNames:
    - portainer.app.homelab.me               # 主域名
  issuerRef:
    name: local-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io