# 通用基础配置（所有环境共享）
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

# 持久化配置（可选）
persistence:
  enabled: true
  size: 10Gi
  storageClass: longhorn  # 引用全局存储类

# 日志基础配置
logs:
  general:
    level: INFO
  access:
    enabled: true

# 从初始文件继承
ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - web
      - websecure
    matchRule: Host(`traefik.app.homelab.me`) && PathPrefix(`/`)
    tls:  # 为dashboard启用TLS
      secretName: traefik-tls  # 引用证书Secret
providers:
  kubernetesGateway:
    enabled: true
gateway:
  namespacePolicy: All