ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - web
      - websecure
    matchRule: Host(`traefik.app.homelab.me`) && PathPrefix(`/`)
    tls:  # 为dashboard启用TLS
      secretName: traefik-tls  # 引用证书Secret
providers:
  kubernetesGateway:
    enabled: true
gateway:
  namespacePolicy: All