# Homepage configuration
# For configuration options, please see:
# https://gethomepage.dev/en/configs/settings/

title: Lou's Homepage
subtitle: Self-hosted Services in a Kubernetes(k3s) Cluster
logo: 
favicon: 
headerStyle: 

theme: dark
colors:
  light:
    primary: "#3b82f6"
    background: "#f8fafc"
  dark:
    primary: "#3b82f6"
    background: "#0f172a"

# Enable the sidebar for navigation
sidebar: true

# Show the search bar
search: true

# Show the theme toggle
themeToggle: true

# Enable grouping by hostname
showHostnames: true

# Show CPU and memory usage bars
showStats: true

# Show the last updated time
showLastUpdated: true

# Show the app version
showAppVersion: true

# Show the clock
showClock: true

# Show the weather
showWeather: true

# Show the status indicator
showStatus: true

# Default status timeout
statusTimeout: 5

# Default status refresh interval
statusRefreshInterval: 30