apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homarr
  namespace: myapps
spec:
  interval: 5m
  chart:
    spec:
      chart: homarr
      version: "2.0.0"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: homarr-values
      valuesKey: values.yaml