# clusters/k3s-homelab/apps/homarr/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homarr
  namespace: myapps  # Homarr 部署的目标命名空间（与你的 ArgoCD 配置一致）
spec:
  interval: 15m  # 每 15 分钟检查一次更新

  # 引用上一步定义的 Helm 仓库源
  chart:
    spec:
      chart: homarr
      version: 5.10.0  # 与你之前使用的版本一致
      sourceRef:
        kind: HelmRepository
        name: homarr
        namespace: flux-system
      interval: 1h  # 每小时检查一次 chart 更新

  # 部署前创建命名空间（如果不存在）
  install:
    createNamespace: true

  # 引用你的 values 文件（从当前仓库读取）
  valuesFrom:
    - kind: ConfigMap
      name: homarr-values  # 后续通过 Kustomize 从本地文件生成
      optional: false

  # 自动同步策略（可选，根据需要调整）
  upgrade:
    remediation:
      retries: 3  # 升级失败时重试 3 次