apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 24h
  timeout: 1h
  chart:
    spec:
      chart: loki
      version: x.x.x
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 5m
  releaseName: loki
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  valuesFrom:
  - kind: ConfigMap
    name: loki-values
  - kind: Secret
    name: minio-credentials
    valuesKey: rootUser
    targetPath: loki.storage_config.aws.access_key_id
  - kind: Secret
    name: minio-credentials
    valuesKey: rootPassword
    targetPath: loki.storage_config.aws.secret_access_key
  - kind: Secret
    name: minio-credentials
    valuesKey: rootUser
    targetPath: loki.storage.s3.access_key_id
  - kind: Secret
    name: minio-credentials
    valuesKey: rootPassword
    targetPath: loki.storage.s3.secret_access_key
