apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: monitoring
spec:
  interval: 24h
  timeout: 1h
  chart:
    spec:
      chart: minio
      version: x.x.x
      sourceRef:
        kind: HelmRepository
        name: minio
      interval: 5m
  releaseName: minio
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    mode: standalone
  valuesFrom:
  - kind: ConfigMap
    name: minio-values