apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitea-dashboard-ingress
  namespace: gitea
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`gitea.app.homelab.me`) && PathPrefix(`/`)
      kind: Rule
      services:
      - name: gitea-http
        port: 3000 
  tls:
    secretName: gitea-tls 