tempo:
  deploymentMode: singleBinary  # 单节点模式（适合小规模环境，与Loki一致）
  replicaCount: 1
  storage:
    trace:
      backend: s3
      s3:
        endpoint: minio:9000
        bucket: tempo
        insecure: true
# 持久化配置（若使用本地存储）
persistence:
  enabled: true
  storageClassName: "longhorn"  # 与其他组件共用Longhorn存储类
  size: 10Gi  # 存储容量