apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - HelmRepository.yaml
  - HelmRelease.yaml
configMapGenerator:
  - name: kube-prometheus-stack-values
    files:
      - values.yaml=../../../../values/monitoring/kube-prometheus-stack/kube-prometheus-stack-values.yaml
configurations:
  - KustomizeConfig.yaml