# Kube Prometheus Stack 配置文件
# 版本: 77.10.0
# 最后更新: 

######################################
# 基础配置
######################################
# CRD 管理配置
crd:
  install: true  # 允许 Helm 安装/升级 CRD
  upgrade: true

######################################
# 存储配置
######################################
# 统一配置所有组件的PVC，使用longhorn存储类
# Alertmanager 存储配置
alertmanager:
  alertmanagerSpec:
    # 持久化存储配置
    volumeClaimTemplate:
      spec:
        storageClassName: "longhorn"  # 使用longhorn存储类
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi  # Alertmanager存储容量
    # PVC保留策略（可选，K8s 1.27+支持）
    persistentVolumeClaimRetentionPolicy:
      whenDeleted: Retain
      whenScaled: Retain

# Prometheus 存储配置
prometheus:
  prometheusSpec:
    # 持久化存储配置
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "longhorn"  # 使用longhorn存储类
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 100Gi  # Prometheus存储容量（建议更大）
    # PVC保留策略（可选，K8s 1.27+支持）
    persistentVolumeClaimRetentionPolicy:
      whenDeleted: Retain
      whenScaled: Retain

######################################
# 服务监控配置 (ServiceMonitor)
######################################
  additionalServiceMonitors:
    ###########################################################################
    # 第一部分: 核心集群监控组件
    ###########################################################################
    # 1. k8s-monitoring-node-exporter（节点级指标采集）
    ###########################################################################
    - name: k8s-monitoring-node-exporter
      namespace: monitoring  # 与 Prometheus 同命名空间
      selector:
        # 匹配 node-exporter Service 的标签
        matchLabels:
          app.kubernetes.io/name: node-exporter
          app.kubernetes.io/instance: k8s-monitoring  # 对应 k8s-monitoring Chart 的实例名
      namespaceSelector:
        # 目标 Service 所在命名空间
        matchNames:
          - monitoring
      endpoints:
        - port: metrics  # 端口名称（非端口号）
          interval: 15s  # 指标抓取间隔
          path: /metrics  # 默认指标路径
          scrapeTimeout: 10s  # 抓取超时（小于间隔）

    ###########################################################################
    # 2. k8s-monitoring-kube-state-metrics（K8s 资源对象指标）
    ###########################################################################
    - name: k8s-monitoring-kube-state-metrics
      namespace: monitoring
      selector:
        matchLabels:
          app.kubernetes.io/name: kube-state-metrics
          app.kubernetes.io/instance: k8s-monitoring
      namespaceSelector:
        matchNames:
          - monitoring
      endpoints:
        - port: http  # 端口名称
          interval: 15s
          path: /metrics  # 默认指标路径
          scrapeTimeout: 10s

    ###########################################################################
    # 第二部分: Alloy 组件监控
    ###########################################################################
    # 3. k8s-monitoring-alloy-metrics（Alloy 指标处理模块）
    ###########################################################################
    - name: k8s-monitoring-alloy-metrics
      namespace: monitoring
      selector:
        matchLabels:
          app.kubernetes.io/name: alloy-metrics
          app.kubernetes.io/instance: k8s-monitoring-alloy-metrics
      namespaceSelector:
        matchNames:
          - monitoring
      endpoints:
        - port: http-metrics  # 端口名称
          interval: 15s
          path: /metrics  # 暴露 Alloy 自身运行状态及转发的指标
          scrapeTimeout: 10s

    ###########################################################################
    # 4. k8s-monitoring-alloy-singleton（Alloy 单例组件）
    ###########################################################################
    - name: k8s-monitoring-alloy-singleton
      namespace: monitoring
      selector:
        matchLabels:
          app.kubernetes.io/name: alloy-singleton
          app.kubernetes.io/instance: k8s-monitoring-alloy-singleton
      namespaceSelector:
        matchNames:
          - monitoring
      endpoints:
        - port: http-metrics  # 端口名称
          interval: 15s
          path: /metrics  # 暴露全局任务运行状态
          scrapeTimeout: 10s

    ###########################################################################
    # 5. k8s-monitoring-alloy-operator（Alloy 控制器）
    ###########################################################################
    - name: k8s-monitoring-alloy-operator
      namespace: monitoring
      selector:
        matchLabels:
          app.kubernetes.io/name: alloy-operator
          app.kubernetes.io/instance: k8s-monitoring
      namespaceSelector:
        matchNames:
          - monitoring
      endpoints:
        - port: metrics  # 端口名称
          interval: 30s  # Operator 指标变化较慢，可适当延长间隔
          path: /metrics  # 默认指标路径
          scrapeTimeout: 10s

    ###########################################################################
    # 6. k8s-monitoring-alloy-logs（Alloy 日志收集组件）
    ###########################################################################
    - name: k8s-monitoring-alloy-logs
      namespace: monitoring
      selector:
        matchLabels:
          app.kubernetes.io/name: alloy-logs
          app.kubernetes.io/instance: k8s-monitoring-alloy-logs
      namespaceSelector:
        matchNames:
          - monitoring
      endpoints:
        - port: http-metrics  # 端口名称（不是端口号）
          interval: 15s
          path: /metrics  # 默认指标路径
          scrapeTimeout: 10s

    ###########################################################################
    # 7. k8s-monitoring-alloy-receiver（Alloy 数据接收组件）
    ###########################################################################
    - name: k8s-monitoring-alloy-receiver
      namespace: monitoring
      selector:
        matchLabels:
          app.kubernetes.io/name: alloy-receiver
          app.kubernetes.io/instance: k8s-monitoring-alloy-receiver
      namespaceSelector:
        matchNames:
          - monitoring
      endpoints:
        - port: http-metrics  # 端口名称（不是端口号）
          interval: 15s
          path: /metrics  # 默认指标路径
          scrapeTimeout: 10s

    ###########################################################################
    # 第三部分: 可观测性后端服务
    ###########################################################################
    # 8. loki（日志存储与查询组件）
    ###########################################################################
    - name: loki
      namespace: monitoring
      selector:
        matchLabels:
          app.kubernetes.io/name: loki
          app.kubernetes.io/instance: loki
      namespaceSelector:
        matchNames:
          - monitoring
      endpoints:
        - port: http-metrics  # 端口名称（不是端口号）
          interval: 15s
          path: /metrics  # 默认指标路径
          scrapeTimeout: 10s

    ###########################################################################
    # 9. tempo（追踪数据存储与查询组件）
    ###########################################################################
    - name: tempo
      namespace: monitoring
      selector:
        matchLabels:
          app.kubernetes.io/name: tempo
          app.kubernetes.io/instance: tempo
      namespaceSelector:
        matchNames:
          - monitoring
      endpoints:
        - port: tempo-prom-metrics  # 端口名称（不是端口号）
          interval: 15s
          path: /metrics  # 默认指标路径
          scrapeTimeout: 10s

    ###########################################################################
    # 10. minio（对象存储服务）
    ###########################################################################
    - name: minio
      namespace: monitoring
      selector:
        matchLabels:
          app: minio
          release: minio
      namespaceSelector:
        matchNames:
          - monitoring
      endpoints:
        - port: http  # 端口名称（不是端口号）
          interval: 30s  # 存储服务指标变化较慢
          path: /minio/v2/metrics/cluster  # MinIO 集群指标路径
          scrapeTimeout: 10s

    ###########################################################################
    # 11. uptime-kuma（服务健康监控组件）
    ###########################################################################
    - name: uptime-kuma
      namespace: monitoring
      selector:
        matchLabels:
          app.kubernetes.io/name: uptime-kuma
          app.kubernetes.io/instance: uptime-kuma
      namespaceSelector:
        matchNames:
          - monitoring
      endpoints:
        - port: http  # 端口名称（不是端口号）
          interval: 30s
          path: /metrics  # 默认指标路径
          scrapeTimeout: 10s

######################################
# Pod 监控配置 (PodMonitor)
######################################
  additionalPodMonitors:
    # 1. k8s-monitoring-beyla（eBPF 自动检测组件）
    - name: k8s-monitoring-beyla
      namespace: monitoring
      selector:
        matchLabels:
          app.kubernetes.io/name: beyla
          app.kubernetes.io/instance: k8s-monitoring
      podMetricsEndpoints:
        - port: metrics  # 对应 Beyla Pod 的 metrics 端口
          interval: 15s
          path: /metrics

grafana:
  defaultDashboardsTimezone: Asia/Shanghai
  persistence:
    enabled: true  # 开启Grafana持久化
    storageClassName: "longhorn"  # 使用longhorn存储类
    accessModes: ["ReadWriteOnce"]
    size: 10Gi  # Grafana存储容量
    # existingClaim: ""  # 若使用已有PVC，可取消注释并指定名称

nodeExporter:
  enabled: false

kubeStateMetrics:
  enabled: false # 改用 Alloy 采集 Kubernetes 资源状态