crd:
  install: true  # 允许 Helm 安装/升级 CRD
  upgrade: true
  
# 统一配置所有组件的PVC，使用longhorn存储类
alertmanager:
  alertmanagerSpec:
    volumeClaimTemplate:
      spec:
        storageClassName: "longhorn"  # 使用longhorn存储类
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi  # Alertmanager存储容量
    # PVC保留策略（可选，K8s 1.27+支持）
    persistentVolumeClaimRetentionPolicy:
      whenDeleted: Retain
      whenScaled: Retain

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "longhorn"  # 使用longhorn存储类
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 100Gi  # Prometheusetheus存储容量（建议更大）
    # PVC保留策略（可选，K8s 1.27+支持）
    persistentVolumeClaimRetentionPolicy:
      whenDeleted: Retain
      whenScaled: Retain
  additionalServiceMonitors:
  - name: k8s-monitoring-node-exporter  # ServiceMonitor 名称
    namespace: monitoring  # 通常与 Prometheus 同命名空间（如 monitoring）
    selector:
      # 匹配 k8s-monitoring 命名空间中 node-exporter Service 的标签
      matchLabels:
        app: node-exporter  # 需与实际 Service 标签一致
    namespaceSelector:
      # 指定目标 Service 所在的命名空间（k8s-monitoring）
      matchNames:
        - k8s-monitoring
    endpoints:
      - port: metrics  # 对应 node-exporter Service 的端口名
        interval: 15s  # 抓取间隔
        path: /metrics  # 指标暴露路径（node-exporter 默认是 /metrics）

grafana:
  persistence:
    enabled: true  # 开启Grafana持久化
    storageClassName: "longhorn"  # 使用longhorn存储类
    accessModes: ["ReadWriteOnce"]
    size: 10Gi  # Grafana存储容量
    # existingClaim: ""  # 若使用已有PVC，可取消注释并指定名称

nodeExporter:
  enabled: false

kubeStateMetrics:
  enabled: false # 改用 Alloy 采集 Kubernetes 资源状态