## 基础配置
global:
  hosts:
    # 全局域名设置为 homelab.me
    domain: app.homelab.me
    # 为 GitLab 主服务指定完整主机名（覆盖默认的 gitlab.${domain}）
    gitlab:
      host: gitlab.app.homelab.me
    # 如果需要其他服务（如 registry、pages 等）也使用该域名前缀，可类似配置
    # registry:
    #   host: registry.app.homelab.me
    pages:
      host: pages.app.homelab.me
    minio:
      host: minio.app.homelab.me
    # 保持 HTTPS 启用（根据实际环境可调整）
    https: true

  # 禁用内置 Ingress 配置，使用 Traefik IngressRoute
  ingress:
    configureCertmanager: false  # 禁用内置 cert-manager 配置
    provider: none               # 不使用内置 Ingress 控制器
    enabled: true                # 保留基础路由配置（供服务发现）
    tls:
      enabled: false             # 由 Traefik + cert-manager 管理 TLS

  # 其他基础配置（根据需求调整）
  # edition: ce  # 使用社区版
  # gitlabVersion: "18.2.1"  # 保持与模板一致的版本

  minio:
    enabled: true  # 如需外部对象存储，设为 false 并配置 global.appConfig.object_store

  registry:
    # 配置 httpSecret 从 Secret 读取
    httpSecret:
      secret: gitlab-registry-httpsecret  # 对应上面创建的 Secret 名称
      key: httpSecret                     # 对应 Secret 中的 key

  smtp:
    enabled: false  # 启用后需填写 SMTP 信息
    # address: smtp.example.com
    # port: 587
    # user_name: your-email@example.com
    # password:
    #   secret: "smtp-password-secret"
    #   key: password
# 禁用内置组件（如需）
nginx-ingress:
  enabled: false  # 禁用内置 Nginx Ingress

## Settings for the Let's Encrypt ACME Issuer
certmanager-issuer:
#   # The email address to register certificates requested from Let's Encrypt.
#   # Required if using Let's Encrypt.
  email: dummy@email.com
## 组件配置（按需启用/调整）
installCertmanager: false      # 禁用内置 cert-manager 安装

gitlab:
  webservice:
    resources:
      requests:
        cpu: 300m
        memory: "4Gi"  # 提高请求内存（至少比当前高50%）
      limits:
        cpu: 1000m
        memory: "6Gi"  # 提高内存上限（避免被OOM杀死）
    readinessProbe:
      initialDelaySeconds: 120  # 延长至2分钟，确保服务有足够时间启动
      timeoutSeconds: 5
      period: 10
    livenessProbe:
      initialDelaySeconds: 180  # 延长存活探针初始延迟
      timeoutSeconds: 30
    appConfig:
      # 新增：声明静态资源路径及访问权限
      static_files:
        enabled: true
        paths:
          - /assets  # 允许 /assets 下的所有资源公开访问
        skip_authentication: true  # 无需登录即可访问

## 禁用不需要的内置服务（如已使用外部服务）
postgresql:
  enabled: true  # 如需外部 PostgreSQL，设为 false 并配置 global.psql
redis:
  install: true  # 如需外部 Redis，设为 false 并配置 global.redis

## Pages 配置（如需启用）
pages:
  enabled: false  # 根据需求启用
  # 如需启用，需额外创建对应的 IngressRoute