apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: monitoring
spec:
  interval: 24h
  timeout: 1h
  chart:
    spec:
      chart: alloy
      version: x.x.x
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 5m
  releaseName: alloy
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  valuesFrom:
  - kind: ConfigMap
    name: alloy-values