apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr
  namespace: myapps
spec:
  interval: 1m
  timeout: 5m
  chart:
    spec:
      chart: homarr
      version: 5.9.1
      sourceRef:
        kind: HelmRepository
        name: homarr-chart
      interval: 5m
  releaseName: homarr
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  valuesFrom:
    - kind: GitRepository
      name: my-values-repo  # 关联上面定义的 GitRepository
      valuesKey: values/applications/homarr/homarr-values.yaml  # Git 仓库中 values 文件的相对路径