apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr
  namespace: myapps
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: homarr
      version: 'latest'
      sourceRef:
        kind: HelmRepository
        name: homarr-chart
      interval: 5m
  releaseName: homarr
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    replicaCount: 1
    service:
      type: ClusterIP
      port: 7575
    ingress:
      enabled: false