# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapps
configMapGenerator:
  - name: homarr-values  # ConfigMap 名称
    files:
      - values.yaml=homarr-values.yaml
    options:
      labels:
        app: homarr