apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
namespace: myapps
resources:
- source.yaml
- release.yaml
configMapGenerator:
- name: homarr-values
  namespace: myapps
  behavior: replace
  files:
  - homarr-values.yaml
replacements:
- source:
    kind: Namespace
    name: myapps
    fieldPath: metadata.name
  targets:
  - select:
      kind: ConfigMap
      name: homarr-values
    fieldPaths:
    - metadata.namespace