apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapps
resources:
- source.yaml
- release.yaml
configMapGenerator:
- name: homarr-values
  namespace: myapps
  files:
  - homarr-values.yaml