apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homarr
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: myapps
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./clusters/k3s-homelab/applications/homarr"
  prune: true
  timeout: 1m
  resources:
    - HelmRepository.yaml
    - HelmRelease.yaml
    - HelmRelease.yaml