apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr
  namespace: myapps
spec:
  interval: 1h
  chart:
    spec:
      chart: homarr
      version: ">=1.0.0"
      sourceRef:
        kind: HelmRepository
        name: homarr
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: homarr-values
    namespace: myapps
    valuesKey: values.yaml