apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
resources:
- source.yaml
- release.yaml
configMapGenerator:
- name: homarr-values
  namespace: myapps
  behavior: merge
  files:
  - values.yaml=homarr-values.yaml