apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
namespace: myapps
resources:
- source.yaml
- release.yaml
configMapGenerator:
- name: homarr-values
  files:
  - values.yaml=../../../../values/applications/homarr/homarr-values.yaml