apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-kustomization-config
  namespace: monitoring
spec:
  patches:
    - target:
        kind: HelmRelease
      patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: alloy
          namespace: monitoring
        spec:
          valuesFrom:
            - kind: ConfigMap
              name: alloy-values