apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homarr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/homarr-labs/charts
    chart: homarr
    targetRevision: 5.10.0
    helm:
      valueFiles:
        - $values/k3s_helm_configs/values/applications/homarr/homarr-values.yaml
  sources:
    - repoURL: https://github.com/L128/k3s_helm_configs.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: myapps
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true