releases:
  - name: traefik
    chart: traefik/traefik
    version: 28.0.0
    namespace: traefik-system
    condition: traefik.enabled
    values:
      - values/infrastructure/traefik/base.yaml
      - values/infrastructure/traefik/{{ .Environment.Name }}.yaml
    set:
      - name: ports.websecure.enabled
        value: true
      - name: ports.websecure.port
        value: 443
      - name: ports.websecure.exposedPort
        value: 443
      - name: ports.websecure.protocol
        value: TCP
      - name: providers.kubernetesCRD.enabled
        value: true
      - name: providers.kubernetesIngress.enabled
        value: false  # 禁用传统Ingress支持
