apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: homepage
  namespace: homepage
spec:
  image: ghcr.io/gethomepage/homepage
  interval: 24h0m0s
  secretRef:
    name: ghcr-auth