apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
- Certificate.yaml
- ClusterRole.yaml
- ClusterRoleBinding.yaml
- Deployment.yaml
- ImagePolicy.yaml
- ImageRepository.yaml
- IngressRoute.yaml
- Namespace.yaml
- Secret.yaml
- Service.yaml
- ServiceAccount.yaml

configMapGenerator:
- name: homepage
  files:
  - config/kubernetes.yaml
  - config/settings.yaml
  - config/custom.css
  - config/custom.js
  - config/bookmarks.yaml
  - config/services.yaml
  - config/widgets.yaml
  - config/docker.yaml

commonLabels:
  app.kubernetes.io/name: homepage