service:
  type: ClusterIP
persistence:
  enabled: true
  size: 10Gi
ingress:
  enabled: true
  hosts:
    - host: "portainer.app.homelab.me"
      paths:
        - path: "/"
          port: 9000
  tls: 
      - secretName: portainer-tls
        hosts:
          - portainer.app.homelab.me