apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 24h
  timeout: 5m
  chart:
    spec:
      chart: cert-manager
      version: x.x.x
      sourceRef:
        kind: HelmRepository
        name: jetstack
      interval: 5m
  releaseName: cert-manager
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  valuesFrom:
  - kind: ConfigMap
    name: cert-manager-values