env:
  # -- Your local time zone
  TZ: "Asia/Shanghai"
  
database:
#   # -- Enable external database
#   externalDatabaseEnabled: true
  externalDatabaseEnabled: false

persistence:
  homarrDatabase:
    enabled: true
    storageClassName: "default"
    size: "1Gi"

  # Ingress configuration
ingress:
  # -- Enable ingress
  enabled: true
  # -- Ingress class name
  ingressClassName: "traefik"
  # -- Ingress annotations
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  # -- Ingress hosts configuration
  hosts:
    - host: homarr.app.homelab.me
      paths:
        - path: /
          port: 7575

  # -- Ingress TLS configuration
  tls: 
   - secretName: myapps-tls
     hosts:
       - homarr.app.homelab.me