apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.18.0
        # 将 imagePullPolicy 移至容器配置内
        imagePullPolicy: Always
        args:
          - --source=crd
          # - --crd-source-api-version=traefik.io/v1alpha1
          - --crd-source-kind=IngressRoute
          - --domain-filter=homelab.me
          - --provider=coredns
          - --log-level=debug
          - --request-timeout=60s
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
- apiGroups: ["traefik.io"]
  resources: ["ingressroutes", "ingressroutetcps", "ingressrouteudps"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["configmaps", "events"]
  verbs: ["get", "update", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: external-dns
  apiGroup: rbac.authorization.k8s.io
    