apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitea-cert
  namespace: gitea
spec:
  secretName: gitea-tls
  commonName: app.homelab.me
  dnsNames:
    - gitea.app.homelab.me               # 主域名
  issuerRef:
    name: local-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io