apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-cert
  namespace: longhorn-system
spec:
  secretName: longhorn-tls
  commonName: app.homelab.me
  dnsNames:
    - longhorn.app.homelab.me               # 主域名
  issuerRef:
    name: local-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io