apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-cert
  namespace: monitoring
spec:
  secretName: monitoring-tls
  commonName: app.homelab.me
  dnsNames:
    - uptimekuma.app.homelab.me    
  issuerRef:
    name: local-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io