# standalone-configs/certs/argocd-cert.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-cert
  namespace: argocd  # ArgoCD 默认命名空间
spec:
  secretName: argocd-server-tls  # 与 ArgoCD 配置中引用的 secret 名称一致
  commonName: argocd.app.homelab.me
  dnsNames:
    - argocd.app.homelab.me       # ArgoCD 服务器域名
    - argocd-repo-server.app.homelab.me  # 仓库服务器域名
    - argocd-dex-server.app.homelab.me    # Dex 认证服务器域名（如需）
  issuerRef:
    name: local-ca-issuer  # 复用现有本地 CA 签发者
    kind: ClusterIssuer
    group: cert-manager.io
---
# 如需单独为仓库服务器配置证书可添加此段
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-repo-server-cert
  namespace: argocd
spec:
  secretName: argocd-repo-server-tls
  commonName: argocd-repo-server.app.homelab.me
  dnsNames:
    - argocd-repo-server.app.homelab.me
  issuerRef:
    name: local-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io