cluster:
  name: k3s-homelab
clusterMetrics:
  enabled: true
clusterEvents:
  enabled: true
nodeLogs:
  enabled: true
podLogs:
  enabled: true
podLogsViaKubernetesApi:
  enabled: true
applicationObservability:
  enabled: true
autoInstrumentation:
  enabled: true
annotationAutodiscovery:
  enabled: true
prometheusOperatorObjects:
  enabled: true
profiling:
  enabled: true
profilesReceiver:
  enabled: true
selfReporting:
  enabled: true
alloy-metrics:
  enabled: true
alloy-singleton:
  enabled: true
alloy-logs:
  enabled: true
alloy-receiver:
  enabled: true
alloy-profiles:
  enabled: true